# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketplace_processor/protobuf/payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from marketplace_processor.protobuf import rule_pb2 as marketplace__processor_dot_protobuf_dot_rule__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='marketplace_processor/protobuf/payload.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n,marketplace_processor/protobuf/payload.proto\x1a)marketplace_processor/protobuf/rule.proto\"\xb8\x03\n\x12TransactionPayload\x12\x35\n\x0cpayload_type\x18\x01 \x01(\x0e\x32\x1f.TransactionPayload.PayloadType\x12&\n\x0e\x63reate_account\x18\x02 \x01(\x0b\x32\x0e.CreateAccount\x12\"\n\x0c\x63reate_asset\x18\x03 \x01(\x0b\x32\x0c.CreateAsset\x12&\n\x0e\x63reate_holding\x18\x04 \x01(\x0b\x32\x0e.CreateHolding\x12\"\n\x0c\x63reate_offer\x18\x05 \x01(\x0b\x32\x0c.CreateOffer\x12\"\n\x0c\x61\x63\x63\x65pt_offer\x18\n \x01(\x0b\x32\x0c.AcceptOffer\x12 \n\x0b\x63lose_offer\x18\x0b \x01(\x0b\x32\x0b.CloseOffer\"\x8c\x01\n\x0bPayloadType\x12\x0e\n\nTYPE_UNSET\x10\x00\x12\x12\n\x0e\x43REATE_ACCOUNT\x10\x02\x12\x10\n\x0c\x43REATE_ASSET\x10\x03\x12\x12\n\x0e\x43REATE_HOLDING\x10\x04\x12\x10\n\x0c\x43REATE_OFFER\x10\x05\x12\x10\n\x0c\x41\x43\x43\x45PT_OFFER\x10\n\x12\x0f\n\x0b\x43LOSE_OFFER\x10\x0b\"3\n\rCreateAccount\x12\r\n\x05label\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"F\n\x0b\x43reateAsset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x05rules\x18\x03 \x03(\x0b\x32\x05.Rule\"`\n\rCreateHolding\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05\x61sset\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\x12\"\xa5\x01\n\x0b\x43reateOffer\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x17\n\x0fsource_quantity\x18\x05 \x01(\x12\x12\x0e\n\x06target\x18\x06 \x01(\t\x12\x17\n\x0ftarget_quantity\x18\x07 \x01(\x12\x12\x14\n\x05rules\x18\x08 \x03(\x0b\x32\x05.Rule\"H\n\x0b\x41\x63\x63\x65ptOffer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\r\n\x05\x63ount\x18\x04 \x01(\x04\"\x18\n\nCloseOffer\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3')
  ,
  dependencies=[marketplace__processor_dot_protobuf_dot_rule__pb2.DESCRIPTOR,])



_TRANSACTIONPAYLOAD_PAYLOADTYPE = _descriptor.EnumDescriptor(
  name='PayloadType',
  full_name='TransactionPayload.PayloadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ACCOUNT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ASSET', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_HOLDING', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_OFFER', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPT_OFFER', index=5, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_OFFER', index=6, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=392,
  serialized_end=532,
)
_sym_db.RegisterEnumDescriptor(_TRANSACTIONPAYLOAD_PAYLOADTYPE)


_TRANSACTIONPAYLOAD = _descriptor.Descriptor(
  name='TransactionPayload',
  full_name='TransactionPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_type', full_name='TransactionPayload.payload_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_account', full_name='TransactionPayload.create_account', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_asset', full_name='TransactionPayload.create_asset', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_holding', full_name='TransactionPayload.create_holding', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_offer', full_name='TransactionPayload.create_offer', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accept_offer', full_name='TransactionPayload.accept_offer', index=5,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='close_offer', full_name='TransactionPayload.close_offer', index=6,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRANSACTIONPAYLOAD_PAYLOADTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=532,
)


_CREATEACCOUNT = _descriptor.Descriptor(
  name='CreateAccount',
  full_name='CreateAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='CreateAccount.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='CreateAccount.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=534,
  serialized_end=585,
)


_CREATEASSET = _descriptor.Descriptor(
  name='CreateAsset',
  full_name='CreateAsset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateAsset.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='CreateAsset.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rules', full_name='CreateAsset.rules', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=657,
)


_CREATEHOLDING = _descriptor.Descriptor(
  name='CreateHolding',
  full_name='CreateHolding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CreateHolding.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='CreateHolding.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='CreateHolding.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='asset', full_name='CreateHolding.asset', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='CreateHolding.quantity', index=4,
      number=5, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=659,
  serialized_end=755,
)


_CREATEOFFER = _descriptor.Descriptor(
  name='CreateOffer',
  full_name='CreateOffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CreateOffer.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='CreateOffer.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='CreateOffer.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='CreateOffer.source', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_quantity', full_name='CreateOffer.source_quantity', index=4,
      number=5, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='CreateOffer.target', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_quantity', full_name='CreateOffer.target_quantity', index=6,
      number=7, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rules', full_name='CreateOffer.rules', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=758,
  serialized_end=923,
)


_ACCEPTOFFER = _descriptor.Descriptor(
  name='AcceptOffer',
  full_name='AcceptOffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AcceptOffer.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='AcceptOffer.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='AcceptOffer.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='AcceptOffer.count', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=925,
  serialized_end=997,
)


_CLOSEOFFER = _descriptor.Descriptor(
  name='CloseOffer',
  full_name='CloseOffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CloseOffer.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=999,
  serialized_end=1023,
)

_TRANSACTIONPAYLOAD.fields_by_name['payload_type'].enum_type = _TRANSACTIONPAYLOAD_PAYLOADTYPE
_TRANSACTIONPAYLOAD.fields_by_name['create_account'].message_type = _CREATEACCOUNT
_TRANSACTIONPAYLOAD.fields_by_name['create_asset'].message_type = _CREATEASSET
_TRANSACTIONPAYLOAD.fields_by_name['create_holding'].message_type = _CREATEHOLDING
_TRANSACTIONPAYLOAD.fields_by_name['create_offer'].message_type = _CREATEOFFER
_TRANSACTIONPAYLOAD.fields_by_name['accept_offer'].message_type = _ACCEPTOFFER
_TRANSACTIONPAYLOAD.fields_by_name['close_offer'].message_type = _CLOSEOFFER
_TRANSACTIONPAYLOAD_PAYLOADTYPE.containing_type = _TRANSACTIONPAYLOAD
_CREATEASSET.fields_by_name['rules'].message_type = marketplace__processor_dot_protobuf_dot_rule__pb2._RULE
_CREATEOFFER.fields_by_name['rules'].message_type = marketplace__processor_dot_protobuf_dot_rule__pb2._RULE
DESCRIPTOR.message_types_by_name['TransactionPayload'] = _TRANSACTIONPAYLOAD
DESCRIPTOR.message_types_by_name['CreateAccount'] = _CREATEACCOUNT
DESCRIPTOR.message_types_by_name['CreateAsset'] = _CREATEASSET
DESCRIPTOR.message_types_by_name['CreateHolding'] = _CREATEHOLDING
DESCRIPTOR.message_types_by_name['CreateOffer'] = _CREATEOFFER
DESCRIPTOR.message_types_by_name['AcceptOffer'] = _ACCEPTOFFER
DESCRIPTOR.message_types_by_name['CloseOffer'] = _CLOSEOFFER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionPayload = _reflection.GeneratedProtocolMessageType('TransactionPayload', (_message.Message,), dict(
  DESCRIPTOR = _TRANSACTIONPAYLOAD,
  __module__ = 'marketplace_processor.protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:TransactionPayload)
  ))
_sym_db.RegisterMessage(TransactionPayload)

CreateAccount = _reflection.GeneratedProtocolMessageType('CreateAccount', (_message.Message,), dict(
  DESCRIPTOR = _CREATEACCOUNT,
  __module__ = 'marketplace_processor.protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateAccount)
  ))
_sym_db.RegisterMessage(CreateAccount)

CreateAsset = _reflection.GeneratedProtocolMessageType('CreateAsset', (_message.Message,), dict(
  DESCRIPTOR = _CREATEASSET,
  __module__ = 'marketplace_processor.protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateAsset)
  ))
_sym_db.RegisterMessage(CreateAsset)

CreateHolding = _reflection.GeneratedProtocolMessageType('CreateHolding', (_message.Message,), dict(
  DESCRIPTOR = _CREATEHOLDING,
  __module__ = 'marketplace_processor.protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateHolding)
  ))
_sym_db.RegisterMessage(CreateHolding)

CreateOffer = _reflection.GeneratedProtocolMessageType('CreateOffer', (_message.Message,), dict(
  DESCRIPTOR = _CREATEOFFER,
  __module__ = 'marketplace_processor.protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateOffer)
  ))
_sym_db.RegisterMessage(CreateOffer)

AcceptOffer = _reflection.GeneratedProtocolMessageType('AcceptOffer', (_message.Message,), dict(
  DESCRIPTOR = _ACCEPTOFFER,
  __module__ = 'marketplace_processor.protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:AcceptOffer)
  ))
_sym_db.RegisterMessage(AcceptOffer)

CloseOffer = _reflection.GeneratedProtocolMessageType('CloseOffer', (_message.Message,), dict(
  DESCRIPTOR = _CLOSEOFFER,
  __module__ = 'marketplace_processor.protobuf.payload_pb2'
  # @@protoc_insertion_point(class_scope:CloseOffer)
  ))
_sym_db.RegisterMessage(CloseOffer)


# @@protoc_insertion_point(module_scope)
