# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketplace_transaction/protobuf/offer_history.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='marketplace_transaction/protobuf/offer_history.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n4marketplace_transaction/protobuf/offer_history.proto\"4\n\x0cOfferHistory\x12\x10\n\x08offer_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\"7\n\x15OfferHistoryContainer\x12\x1e\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\r.OfferHistoryb\x06proto3')
)




_OFFERHISTORY = _descriptor.Descriptor(
  name='OfferHistory',
  full_name='OfferHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offer_id', full_name='OfferHistory.offer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='OfferHistory.account_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=108,
)


_OFFERHISTORYCONTAINER = _descriptor.Descriptor(
  name='OfferHistoryContainer',
  full_name='OfferHistoryContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='OfferHistoryContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=165,
)

_OFFERHISTORYCONTAINER.fields_by_name['entries'].message_type = _OFFERHISTORY
DESCRIPTOR.message_types_by_name['OfferHistory'] = _OFFERHISTORY
DESCRIPTOR.message_types_by_name['OfferHistoryContainer'] = _OFFERHISTORYCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OfferHistory = _reflection.GeneratedProtocolMessageType('OfferHistory', (_message.Message,), dict(
  DESCRIPTOR = _OFFERHISTORY,
  __module__ = 'marketplace_transaction.protobuf.offer_history_pb2'
  # @@protoc_insertion_point(class_scope:OfferHistory)
  ))
_sym_db.RegisterMessage(OfferHistory)

OfferHistoryContainer = _reflection.GeneratedProtocolMessageType('OfferHistoryContainer', (_message.Message,), dict(
  DESCRIPTOR = _OFFERHISTORYCONTAINER,
  __module__ = 'marketplace_transaction.protobuf.offer_history_pb2'
  # @@protoc_insertion_point(class_scope:OfferHistoryContainer)
  ))
_sym_db.RegisterMessage(OfferHistoryContainer)


# @@protoc_insertion_point(module_scope)
